### ISSUE TITLE
按照quick start的方法启动失败

### ISSUE THREAD

**Issue by xyy9949** [stateIs0/lu-raft-kv#21]
您好，我按照quick start的说明在idea中依次配置了多个启动项，加入 -DserverPort=8775，8776，8777等不同端口，但是我始终只能正常启动一个节点。我在macOS和ubuntu上都会出现这个问题。

<img width="713" alt="截屏2023-04-25 22 40 57" src="https://user-images.githubusercontent.com/55914932/234312849-1165302e-1238-496f-bc96-9c03546bf740.png">
<img width="712" alt="截屏2023-04-25 22 41 09" src="https://user-images.githubusercontent.com/55914932/234312908-ba563c77-35a4-4a62-9d96-685e828a10c5.png">
以上是我两个节点的启动项配置。

Exception in thread "main" java.lang.ExceptionInInitializerError
	at cn.think.in.java.impl.DefaultStateMachine.getInstance(DefaultStateMachine.java:72)
	at cn.think.in.java.constant.StateMachineSaveType.<clinit>(StateMachineSaveType.java:32)
	at cn.think.in.java.RaftNodeBootStrap.boot(RaftNodeBootStrap.java:58)
	at cn.think.in.java.RaftNodeBootStrap.main(RaftNodeBootStrap.java:38)
Caused by: java.lang.RuntimeException: org.rocksdb.RocksDBException: While lock file: ./rocksDB-raft/null/stateMachine/LOCK: Resource temporarily unavailable
	at cn.think.in.java.impl.DefaultStateMachine.<init>(DefaultStateMachine.java:67)
	at cn.think.in.java.impl.DefaultStateMachine.<init>(DefaultStateMachine.java:36)
	at cn.think.in.java.impl.DefaultStateMachine$DefaultStateMachineLazyHolder.<clinit>(DefaultStateMachine.java:88)
	... 4 more
Caused by: org.rocksdb.RocksDBException: While lock file: ./rocksDB-raft/null/stateMachine/LOCK: Resource temporarily unavailable
	at org.rocksdb.RocksDB.open(Native Method)
	at org.rocksdb.RocksDB.open(RocksDB.java:231)
	at cn.think.in.java.impl.DefaultStateMachine.<init>(DefaultStateMachine.java:65)
	... 6 more

Process finished with exit code 1
以上是我出现的错误的日志。

另外我发现您的 RaftNodeBootStrap 类中并没有对输入的args做任何的处理。这也让我不太理解。希望得到您的解答，谢谢。
<img width="1112" alt="截屏2023-04-25 22 43 59" src="https://user-images.githubusercontent.com/55914932/234313747-11636feb-2a45-4762-a7a9-047802a7bc38.png">

**Comment by stateIs0** [comment]
1. 请使用 oracle jdk8
2. q:《另外我发现您的 RaftNodeBootStrap 类中并没有对输入的args做任何的处理》a: 不支持相关参数哦

**Comment by xyy9949** [comment]
您好，我的代码现在能够正常启动了，非常感谢！
我还有一个问题想要请教：如果我想在RaftClient控制节点的连接和断开来进行一些测试工作，那么应该如何发出request呢？
目前RaftClientRPC这个类中只有get和put两个方法，但是我看到Request的类型中包含RemovePeer和AddPeer。

<img width="845" alt="截屏2023-04-27 00 29 55" src="https://user-images.githubusercontent.com/55914932/234641738-04264744-8242-4de0-9711-ee3675c8288b.png">

应该是类似RaftClientRPC中get和put方法，然后修改Request r的信息。

<img width="895" alt="截屏2023-04-27 00 35 02" src="https://user-images.githubusercontent.com/55914932/234643098-62a27acd-bf15-4075-874f-240fe979c205.png">
希望您能解答，谢谢。

**Comment by xyy9949** [comment]
目前只能通过手动的方式开启关闭节点

**Comment by GalaxDust** [comment]
> 您好，我的代码现在能够正常启动了，非常感谢！ 我还有一个问题想要请教：如果我想在RaftClient控制节点的连接和断开来进行一些测试工作，那么应该如何发出request呢？ 目前RaftClientRPC这个类中只有get和put两个方法，但是我看到Request的类型中包含RemovePeer和AddPeer。
> 
> <img alt="截屏2023-04-27 00 29 55" width="845" src="https://user-images.githubusercontent.com/55914932/234641738-04264744-8242-4de0-9711-ee3675c8288b.png">
> 
> 应该是类似RaftClientRPC中get和put方法，然后修改Request r的信息。
> 
> <img alt="截屏2023-04-27 00 35 02" width="895" src="https://user-images.githubusercontent.com/55914932/234643098-62a27acd-bf15-4075-874f-240fe979c205.png">
> 
> 希望您能解答，谢谢。

我在启动的时候也遇到了这个问题请问老哥你是怎么解决的
