### ISSUE TITLE
客户端启动报错

### ISSUE THREAD

**Issue by hqlalala** [stateIs0/lu-raft-kv#27]
Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.remoting Log4j ]
2023-09-10 16:42:07,599 main  INFO [com.alipay.sofa.common.log:report:30] - Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.remoting Log4j ]
Exception in thread "main" java.lang.NoClassDefFoundError: com/caucho/hessian/io/SerializerFactory
	at com.alipay.remoting.serialization.HessianSerializer.<init>(HessianSerializer.java:36)
	at com.alipay.remoting.serialization.SerializerManager.<clinit>(SerializerManager.java:36)
	at com.alipay.remoting.rpc.protocol.RpcRequestCommand.serializeContent(RpcRequestCommand.java:132)
	at com.alipay.remoting.rpc.RpcCommand.serialize(RpcCommand.java:105)
	at com.alipay.remoting.rpc.RpcRemoting.toRemotingCommand(RpcRemoting.java:353)
	at com.alipay.remoting.rpc.RpcRemoting.invokeSync(RpcRemoting.java:179)
	at com.alipay.remoting.rpc.RpcClientRemoting.invokeSync(RpcClientRemoting.java:72)
	at com.alipay.remoting.rpc.RpcRemoting.invokeSync(RpcRemoting.java:143)
	at com.alipay.remoting.rpc.RpcClient.invokeSync(RpcClient.java:219)
	at cn.think.in.java.raft.common.rpc.DefaultRpcClient.send(DefaultRpcClient.java:42)
	at cn.think.in.java.raft.common.rpc.DefaultRpcClient.send(DefaultRpcClient.java:35)
	at cn.think.in.java.raft.client.RaftClientRPC.put(RaftClientRPC.java:89)
	at cn.think.in.java.raft.client.RaftClient1.main(RaftClient1.java:38)
Caused by: java.lang.ClassNotFoundException: com.caucho.hessian.io.SerializerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 13 more

客户端发送消息失败

**Comment by leakey0626** [comment]
解决了吗？看起来像是依赖出了问题

**Comment by hqlalala** [comment]
已经解决了，客户端里的依赖和服务端不一致

**Comment by ldzhang1** [comment]
你好，请问一下哪儿不一致啊，我也遇到了这个问题 @hqlalala

**Comment by ldzhang1** [comment]
> 你好，请问一下哪儿不一致啊，我也遇到了这个问题 @hqlalala

已解决

**Comment by Myz-2333** [comment]
我也遇到了，查看maven的依赖库仔细比对，有版本不一致的地方通过更改pom来修复，我出的问题是lombok版本问题，客户端服务端是1.18.2 项目lombok版本是1.18.26 修改之后就好了

**Comment by Sepn1ne** [comment]
> > 你好，请问一下哪儿不一致啊，我也遇到了这个问题 @hqlalala
> 
> 已解决

您好，请问您是怎么解决这个问题的？ @ldzhang1

**Comment by Sepn1ne** [comment]
> > > 你好，请问一下哪儿不一致啊，我也遇到了这个问题 @hqlalala
> > 
> > 
> > 已解决
> 
> 您好，请问您是怎么解决这个问题的？ @ldzhang1

已解决，我这里的解决方法是：在项目结构的库中，可以找到hessian的jar包，右键将这个包给添加到client模块和common模块，之后对maven进行clean install即可。
